// Syllabus Data for StudyOS

const webDevTopics = [
    { id: 'wd_1', title: '1. Introduction', category: 'webdev', isPreCompleted: true },
    { id: 'wd_2', title: '2. Prerequisites', category: 'webdev', isPreCompleted: true },
    { id: 'wd_3', title: '3. HTML (Level 1) - Part A', category: 'webdev', isPreCompleted: true },
    { id: 'wd_4', title: '4. HTML (Level 1) - Part B', category: 'webdev', isPreCompleted: true },
    { id: 'wd_5', title: '5. HTML (Level 2)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_6', title: '6. HTML (Level 3)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_7', title: '7. CSS - Getting Started', category: 'webdev', isPreCompleted: true },
    { id: 'wd_8', title: '8. CSS - Part 2', category: 'webdev', isPreCompleted: true },
    { id: 'wd_9', title: '9. CSS - Part 3', category: 'webdev', isPreCompleted: true },
    { id: 'wd_10', title: '10. CSS - Part 4', category: 'webdev', isPreCompleted: true },
    { id: 'wd_11', title: '11. CSS - Part 5', category: 'webdev', isPreCompleted: true },
    { id: 'wd_12', title: '12. CSS - Part 6', category: 'webdev', isPreCompleted: true },
    { id: 'wd_13', title: '13. Mini Project (CSS)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_14', title: '14. Bootstrap', category: 'webdev', isPreCompleted: true },
    { id: 'wd_15', title: '15. Project (CSS)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_16', title: '16. JavaScript (Part 1)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_17', title: '17. JavaScript (Part 2)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_18', title: '18. JavaScript (Part 3)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_19', title: '19. JavaScript (Part 4)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_20', title: '20. JavaScript (Part 5)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_21', title: '21. JavaScript (Part 6)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_22', title: '22. JavaScript (Part 7)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_23', title: '23. JavaScript (Part 8)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_24', title: '24. JavaScript (Part 9)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_25', title: '25. JavaScript (Part 10)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_26', title: '26. JavaScript (Mini Project)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_27', title: '27. JavaScript (Part 11)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_28', title: '28. JavaScript (Part 12)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_29', title: '29. JavaScript (Part 13)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_30', title: '30. Terminal', category: 'webdev', isPreCompleted: true },
    { id: 'wd_31', title: '31. Git & GitHub', category: 'webdev', isPreCompleted: true },
    { id: 'wd_32', title: '32. Backend 1 (Node.js)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_33', title: '33. Backend 2 (Node : Express)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_34', title: '34. Backend 3 (Node : EJS)', category: 'webdev', isPreCompleted: true },
    { id: 'wd_35', title: '35. Miscellaneous', category: 'webdev' },
    { id: 'wd_36', title: '36. Backend 4 (REST)', category: 'webdev' },
    { id: 'wd_37', title: '37. Starting with SQL', category: 'webdev' },
    { id: 'wd_38', title: '38. SQL Part 2', category: 'webdev' },
    { id: 'wd_39', title: '39. Backend 5 (Node + SQL)', category: 'webdev' },
    { id: 'wd_40', title: '40. MongoDB Installation', category: 'webdev' },
    { id: 'wd_41', title: '41. MongoDB Part 1', category: 'webdev' },
    { id: 'wd_42', title: '42. MongoDB Part 2', category: 'webdev' },
    { id: 'wd_43', title: '43. MongoDB with Express', category: 'webdev' },
    { id: 'wd_44', title: '44. Project Phase 1 Part A', category: 'webdev' },
    { id: 'wd_45', title: '45. Project Phase 1 Part B', category: 'webdev' },
    { id: 'wd_46', title: '46. Backend 6 Middlewares', category: 'webdev' },
    { id: 'wd_47', title: '47. Backend 7 Errors', category: 'webdev' },
    { id: 'wd_48', title: '48. Project Phase 1 Part C', category: 'webdev' },
    { id: 'wd_49', title: '49. Database Relationships', category: 'webdev' },
    { id: 'wd_50', title: '50. Project Phase 2 Part A', category: 'webdev' },
    { id: 'wd_51', title: '51. Project Phase 2 Part B', category: 'webdev' },
    { id: 'wd_52', title: '52. Project Phase 2 Part C', category: 'webdev' },
    { id: 'wd_53', title: '53. Project Phase 2 Part D', category: 'webdev' },
    { id: 'wd_54', title: '54. Project Phase 2 Part E', category: 'webdev' },
    { id: 'wd_55', title: '55. Project Phase 3 Part A', category: 'webdev' },
    { id: 'wd_56', title: '56. Project Phase 3 Part B', category: 'webdev' },
    { id: 'wd_57', title: '57. Project Phase 3 Part C', category: 'webdev' },
    { id: 'wd_58', title: '58. Project Phase 3 Part D', category: 'webdev' },
    { id: 'wd_59', title: '59. React Part 1', category: 'webdev' },
    { id: 'wd_60', title: '60. React Part 2', category: 'webdev' },
    { id: 'wd_61', title: '61. React Part 3', category: 'webdev' },
    { id: 'wd_62', title: '62. React Part 4', category: 'webdev' },
    { id: 'wd_63', title: '63. Miscellaneous', category: 'webdev' },
    { id: 'wd_64', title: '64. React Part 5', category: 'webdev' },
    { id: 'wd_65', title: '65. React Part 6', category: 'webdev' },
    { id: 'wd_66', title: '66. React Major Project', category: 'webdev' },
    { id: 'wd_67', title: '67. Tailwind CSS', category: 'webdev' },
    { id: 'wd_68', title: '68. Redux Toolkit', category: 'webdev' },
    { id: 'wd_69', title: '69. Certificate of Completion', category: 'webdev' }
];

const nimcetMaths = [
    { id: 'nm_1', title: '1. Sets', category: 'maths' },
    { id: 'nm_2', title: '2. Relations', category: 'maths' },
    { id: 'nm_3', title: '3. Functions', category: 'maths' },
    { id: 'nm_4', title: '4. Complex Numbers', category: 'maths' },
    { id: 'nm_5', title: '5. Quadratic Equations', category: 'maths' },
    { id: 'nm_6', title: '6. Theory of Equations', category: 'maths' },
    { id: 'nm_7', title: '7. Sequence and Series', category: 'maths' },
    { id: 'nm_8', title: '8. Permutation and Combination', category: 'maths' },
    { id: 'nm_9', title: '9. Binomial Theorem', category: 'maths' },
    { id: 'nm_10', title: '10. Matrices', category: 'maths' },
    { id: 'nm_11', title: '11. Determinants', category: 'maths' },
    { id: 'nm_12', title: '12. Probability', category: 'maths' },
    { id: 'nm_13', title: '13. Statistics', category: 'maths' },
    { id: 'nm_14', title: '14. Coordinate Geometry', category: 'maths' },
    { id: 'nm_15', title: '15. Straight Line', category: 'maths' },
    { id: 'nm_16', title: '16. Circle', category: 'maths' },
    { id: 'nm_17', title: '17. Conic Sections', category: 'maths' },
    { id: 'nm_18', title: '18. Trigonometry', category: 'maths' },
    { id: 'nm_19', title: '19. Heights and Distances', category: 'maths' },
    { id: 'nm_20', title: '20. Limits', category: 'maths' },
    { id: 'nm_21', title: '21. Continuity', category: 'maths' },
    { id: 'nm_22', title: '22. Differentiability', category: 'maths' },
    { id: 'nm_23', title: '23. Applications of Derivatives', category: 'maths' },
    { id: 'nm_24', title: '24. Indefinite Integration', category: 'maths' },
    { id: 'nm_25', title: '25. Definite Integration', category: 'maths' },
    { id: 'nm_26', title: '26. Differential Equations', category: 'maths' },
    { id: 'nm_27', title: '27. Vector Algebra', category: 'maths' },
    { id: 'nm_28', title: '28. Three Dimensional Geometry', category: 'maths' }
];

const nimcetReasoning = [
    { id: 'nr_1', title: 'Number Series', category: 'reasoning' },
    { id: 'nr_2', title: 'Alphabet Series', category: 'reasoning' },
    { id: 'nr_3', title: 'Coding Decoding', category: 'reasoning' },
    { id: 'nr_4', title: 'Blood Relation', category: 'reasoning' },
    { id: 'nr_5', title: 'Direction Sense', category: 'reasoning' },
    { id: 'nr_6', title: 'Ranking', category: 'reasoning' },
    { id: 'nr_7', title: 'Syllogism', category: 'reasoning' },
    { id: 'nr_8', title: 'Statement Conclusion', category: 'reasoning' },
    { id: 'nr_9', title: 'Statement Assumption', category: 'reasoning' },
    { id: 'nr_10', title: 'Statement Argument', category: 'reasoning' },
    { id: 'nr_11', title: 'Analogy', category: 'reasoning' },
    { id: 'nr_12', title: 'Classification', category: 'reasoning' },
    { id: 'nr_13', title: 'Puzzle', category: 'reasoning' },
    { id: 'nr_14', title: 'Seating Arrangement', category: 'reasoning' },
    { id: 'nr_15', title: 'Clock', category: 'reasoning' },
    { id: 'nr_16', title: 'Calendar', category: 'reasoning' },
    { id: 'nr_17', title: 'Data Sufficiency', category: 'reasoning' },
    { id: 'nr_18', title: 'Critical Reasoning', category: 'reasoning' },
    { id: 'nr_19', title: 'Logical Sequence', category: 'reasoning' },
    { id: 'nr_20', title: 'Venn Diagram', category: 'reasoning' }
];

const nimcetComputer = [
    { id: 'nc_1', title: 'Computer Basics', category: 'computer' },
    { id: 'nc_2', title: 'Computer Organization', category: 'computer' },
    { id: 'nc_3', title: 'CPU', category: 'computer' },
    { id: 'nc_4', title: 'Input Output Devices', category: 'computer' },
    { id: 'nc_5', title: 'Memory', category: 'computer' },
    { id: 'nc_6', title: 'Storage Devices', category: 'computer' },
    { id: 'nc_7', title: 'Operating System', category: 'computer' },
    { id: 'nc_8', title: 'Number System', category: 'computer' },
    { id: 'nc_9', title: 'Boolean Algebra', category: 'computer' },
    { id: 'nc_10', title: 'Data Representation', category: 'computer' },
    { id: 'nc_11', title: 'Computer Networks', category: 'computer' },
    { id: 'nc_12', title: 'Internet', category: 'computer' },
    { id: 'nc_13', title: 'DBMS Basics', category: 'computer' },
    { id: 'nc_14', title: 'MS Office', category: 'computer' },
    { id: 'nc_15', title: 'Computer Security', category: 'computer' }
];

const nimcetEnglish = [
    { id: 'ne_1', title: 'Grammar', category: 'english' },
    { id: 'ne_2', title: 'Vocabulary', category: 'english' },
    { id: 'ne_3', title: 'Articles', category: 'english' },
    { id: 'ne_4', title: 'Prepositions', category: 'english' },
    { id: 'ne_5', title: 'Tenses', category: 'english' },
    { id: 'ne_6', title: 'Subject Verb Agreement', category: 'english' },
    { id: 'ne_7', title: 'Synonyms', category: 'english' },
    { id: 'ne_8', title: 'Antonyms', category: 'english' },
    { id: 'ne_9', title: 'Idioms', category: 'english' },
    { id: 'ne_10', title: 'Reading Comprehension', category: 'english' },
    { id: 'ne_11', title: 'Sentence Correction', category: 'english' }
];

// Special category for Revision
const nimcetRevision = [
    { id: 'nr_rev_1', title: 'Daily Revision & PYQ', category: 'revision', isRecurring: true }
];

const ALL_TOPICS = {
    webdev: webDevTopics,
    maths: nimcetMaths,
    reasoning: nimcetReasoning,
    computer: nimcetComputer,
    english: nimcetEnglish,
    revision: nimcetRevision
};
